### ISSUE TITLE
Enter the letter e

### ISSUE THREAD

**Issue by Kazalo11** [cailaar/guess-my-number#6]
As a user of the website, I expect that when I input data into a text field that is meant for numeric input, the field should only allow me to enter numbers. As a result, I would like the website to be fixed so that the text field only allows numeric input, preventing the entry of any letters or other characters. This will ensure that I can input data accurately and efficiently without any unexpected errors or confusion.

**Comment by cailaar** [comment]
Resolved using` oninput=this.value = this.valueAsNumber`. This not only disables entering the letter e, but also any non-numeric input including spaces, fullstops, negative signs and decimal points.
